name: Generate Snake

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: oliverbuddy
          outputs: dist/snake.svg

      - name: Upload the animation
        uses: actions/upload-artifact@v3
        with:
          name: snake-animation
          path: dist/snake.svg
